frontend:
  - changed-files:
      - any-glob-to-any-file: 'frontend/**'

backend:
  - changed-files:
      - any-glob-to-any-file: 'backend/**'

documentation:
  - changed-files:
      - any-glob-to-any-file: '**/*.md'

type-docs:
  - changed-files:
      - any-glob-to-any-file:
          - '*.md'
          - 'docs/**'

testing:
  - changed-files:
      - any-glob-to-any-file:
          - 'tests/**'
          - 'backend/tests/**'

type-testing:
  - changed-files:
      - any-glob-to-any-file:
          - 'tests/**'
          - 'backend/tests/**'

.github:
  - changed-files:
      - any-glob-to-any-file: '.github/**'
